{
 "title": "my_cool_dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Summary (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Alex-1-server\"}[1m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Alex-2-server\"}[1m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Alex-3-server\"}[1m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Alex-balancer-server\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS Summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"Alex-1-backend\"}[1m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "irate(hits_counter{job=\"Alex-2-backend\"}[1m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "irate(hits_counter{job=\"Alex-3-backend\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Balancer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Alex-balancer-server\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "CPU Alex-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Alex-1-server\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS Alex-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"Alex-1-backend\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Alex-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Alex-2-server\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS Alex-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"Alex-2-backend\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Alex-3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{mode=\"system\",job=\"Alex-3-server\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS Alex-3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(hits_counter{job=\"Alex-3-backend\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}