global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'Alex-balancer-server'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'Alex-1-backend'
    static_configs:
      - targets: ['185.86.145.226:5050']

  - job_name: 'Alex-1-server'
    static_configs:
      - targets: ['185.86.145.226:9100']

  - job_name: 'Alex-2-backend'
    static_configs:
      - targets: ['185.86.146.133:5050']

  - job_name: 'Alex-2-server'
    static_configs:
      - targets: ['185.86.146.133:9100']

  - job_name: 'Alex-3-backend'
    static_configs:
      - targets: ['185.86.147.112:5050']

  - job_name: 'Alex-3-server'
    static_configs:
      - targets: ['185.86.147.112:9100']
